var SearchStoreConstants = {
	SEND_SEARCH: 'SEND_SEARCH',
	SEND_SEARCH_COMPLETED: 'SEND_SEARCH_COMPLETED',
	SEARCH_ERROR: 'SEARCH_ERROR',
	RECEIVE_SEARCH: 'RECEIVE_SEARCH',
	IS_DATA_LOADED: 'IS_DATA_LOADED'
};

module.exports = SearchStoreConstants;